config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  get 'upload' => 'photos#new', :as => :upload
  # resources :categories
  resources :photo_comments, only: [:show, :create, :destroy]
  resources :photos, only: [:new, :create, :update]
  resources :post_comments, only: [:show, :create, :destroy]
  resources :posts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy, :edit]

  resources :posts do
    resources :post_comments
  end

  resources :photos do
    resources :photo_comments
  end

  namespace :admin do
    resources :categories
    resources :photo_comments
    resources :photos
    resources :post_comments
    resources :posts
    resources :sessions, except: [:index, :edit]
    resources :users
  end

  namespace :admin do
    get 'sessions/create'
    get "login" => "sessions#new", :as => "login"
    get "logout" => "sessions#destroy", :as => "logout"
  end

  # namespace :admin do
  #   get "login" => "sessions#new", :as => "login"
  # end

  # namespace :admin do
  #   get 'sessions/create'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#page'
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id                 :integer          not null, primary key
#  image              :string
#  image_title        :string
#  image_file_size    :string
#  image_content_type :string
#  image_description  :string
#  category_id        :integer
#  user_id            :integer
#  tags               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Photo < ApplicationRecord
  has_many :photo_comments
  belongs_to :user
  belongs_to :category,
    primary_key: :id,
    foreign_key: :category_id,
    class_name: :Category

  mount_uploader :image, PhotoUploader
	before_save :update_photo_attributes

	def self.search(query)
    where("image_title like ? OR image_description like ? OR tags like ?", "%#{query}%", "%#{query}%", "%#{query}%")
	end
	
	private
	def update_photo_attributes
		if image.present? && image_changed?
			self.image_content_type = image.file.content_type
			self.image_file_size = image.file.size
		end
	end
  
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :verify_is_admin
  
  def index
    if params[:search]
      @photos = Photo.search(params[:search]).all.order('image_title ASC').paginate(:per_page => 10, :page => params[:page])
    else
      @photos = Photo.all.order('image_title ASC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end

  def new
  	@photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to admin_photos_path
    else
      render 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if params[:photo][:image].blank?
      @photo.image = nil
    end
    if @photo.update(photo_params)
      redirect_to admin_photos_path
    else    
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to admin_photos_path
  end


  private
  def photo_params
    params.require(:photo).permit(:image, :category_id, :image_title, :user_id, :image_description, :image_file_size, :image_content_type, :remote_image_url)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    if params[:search]
      @photos = Photo.search(params[:search]).all.order('image_title ASC').paginate(:per_page => 10, :page => params[:page])
    else
      @photos = Photo.all.order('image_title ASC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end
  
  def new
  	@photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if params[:photo][:image].blank?
      @photo.image = nil
    end
    if @photo.update(photo_params)
      redirect_to admin_photos_path
    else    
      render 'edit'
    end 
  end

  # def destroy
  #   @photo = Photo.find(params[:id])
  #   @photo.destroy
  #   flash[:notice] = "Photo Removed"
  #   redirect_to photos_path
  # end


  private
  def photo_params
    params.require(:photo).permit(:image, :category_id, :image_title, :user_id, :image_description, :image_file_size, :image_content_type, :remote_image_url)
  end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/admin/photos/edit.html.erb
<script>
  $(function() {
    $('textarea').froalaEditor()
  });
</script>

<h2>Edit Photo</h2>

<div class='photo-upload-form'>
	<%= form_for @photo, :html => {:multipart => true} do |f| %>
		<!-- Check for errors -->
		<% if @photo.errors.any? %>
				<% @photo.errors.full_messages.each do |msg| %>
					<!-- Show errors -->
						<div class="alert alert-danger"><%= msg %></div>
				<% end %>
			<% end %>

		<div class="form-group">
			<%= f.label :image_title %>
			<%= f.text_field :image_title ,class:'form-control' %>
		</div>
		
		<div class="form-group">
			<%= f.label :user %>
			<%= f.select :user_id, User.all.order('username ASC').collect {|x| [x.username, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :category %>
			<%= f.select :category_id, Category.all.order('name ASC').collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :image_description %>
			<%= f.text_area :image_description ,class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>
		
		<br>

		<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", admin_photos_path, class:'btn btn-default' %>
	<% end %>
</div>

app/views/admin/photos/index.html.erb
<div id="user_nav" class="pull-right"> 
  <% if current_user %>
    <h5>Logged In as <%= current_user.username.capitalize %></h5>
    <%= link_to 'Log Out', admin_logout_path, class:'btn btn-cancel pull-right' %>
    <% else %>
    <%= link_to 'Log In', admin_login_path, class:'btn btn-info' %>
  <% end %>
</div>

<h2 class="page-header">Manage Photos</h2>
<% if @photos.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Photo Title</th>
      <th>Photo Category</th>
      <th>Date Created</th>
      <th><%= link_to "Add New Photo", new_admin_photo_path, class:'btn btn-addnew' %></th>
    </tr>

    <% @photos.each do |photo|%>
    <tr>
      <td><%= photo.image_title %></td>
      <td><%= photo.category.name %></td>
      <td><%= photo.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= link_to "Edit", edit_admin_photo_path(photo), class:'btn btn-primary'   %> <%= link_to "Delete", admin_photo_path(photo), class:'btn btn-danger',   method: :delete, data: {confirm: 'Are you sure?'}  %></td>
    </tr>
    <% end %>
  </table>
  <%= will_paginate @photos %>
<% else %>
  <p>Sorry, No Photo Was Found.</p>
<% end %>

app/views/admin/photos/new.html.erb
<script>
  $(function() {
    $('textarea').froalaEditor()
  });
</script>

<section>
	<div class="container">

	</div><!-- /.container -->
</section>


<h2>Upload Photo</h2>

<div class='photo-upload-form'>
	<%= form_for @photo, :html => {:multipart => true} do |f| %>
		<!-- Check for errors -->
		<% if @photo.errors.any? %>
				<% @photo.errors.full_messages.each do |msg| %>
					<!-- Show errors -->
						<div class="alert alert-danger"><%= msg %></div>
				<% end %>
			<% end %>

		<div class="form-group">
			<%= f.label :image_title %>
			<%= f.text_field :image_title ,class:'form-control' %>
		</div>
		
		<div class="form-group">
			<%= f.label :user %>
			<%= f.select :user_id, User.all.order('username ASC').collect {|x| [x.username, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :category %>
			<%= f.select :category_id, Category.all.order('name ASC').collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :image_description %>
			<%= f.text_area :image_description ,class:'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>
		
		<br>

		<%= f.submit "Submit", class:'btn btn-primary' %>
		<%=link_to "Cancel", admin_photos_path, class:'btn btn-default' %>
	<% end %>
</div>