config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  get 'upload' => 'photos#new', :as => :upload
  # resources :categories
  resources :photo_comments, only: [:show, :create, :destroy]
  resources :photos, only: [:new, :create, :update]
  resources :post_comments, only: [:show, :create, :destroy]
  resources :posts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy, :edit]

  resources :posts do
    resources :post_comments
  end

  resources :photos do
    resources :photo_comments
  end

  namespace :admin do
    resources :categories
    resources :photo_comments
    resources :photos
    resources :post_comments
    resources :posts
    resources :sessions, except: [:index, :edit]
    resources :users
  end

  namespace :admin do
    get 'sessions/create'
    get "login" => "sessions#new", :as => "login"
    get "logout" => "sessions#destroy", :as => "logout"
  end

  # namespace :admin do
  #   get "login" => "sessions#new", :as => "login"
  # end

  # namespace :admin do
  #   get 'sessions/create'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#page'
end

app/views/partials/_comments.html.erb
<!-- Comments -->
<div class="comments">
  <h2 claass="page-header"><%= @post.comments.length %> Comments</h2>
  <% @post.comments.each do |comment| %>
  <div class="comment">
    <div class="row">
      <div class="col-md-2">
        <%= image_tag("user.jpg") %>
      </div>
      <div class="col-md-10">
        <div class="well">
          <h4><%= comment.name %><span>/<%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></span></h4>
          <%= comment.body %>
        </div>
      </div>
    </div>
  </div>
  <% end %>      

  <div class="well add-comment">
    <h2 class="page-header">Add Comment</h2>
    <%= form_for([@post, @post.comments.build]) do |f| %>
  
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :body %><br>
        <%= f.text_area :body, class:'form-control' %>
      </div>
       <div class="form-group">
        <%= f.submit "Submit", class:'btn btn-primary' %>
      </div>
  <% end %>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="footer">
  <div>
    <ul>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
    <ul>
      <li><a href="#"><img src="https://res.cloudinary.com/swy/image/upload/v1500279538/images/mail.svg"></a></li>
      <li><a href="#"><img src="https://res.cloudinary.com/swy/image/upload/v1500279538/images/facebook.svg"></a></li>
      <li><a href="#"><img src="https://res.cloudinary.com/swy/image/upload/v1500279538/images/twitter.svg"></a></li>
      <li><%= link_to "Admin Login", new_admin_session_path, class:'btn btn-primary pull-right' %></li>
    </ul>
    <ul>
      <li>cheekChubby ©</li>
    </ul>
  </div>
</div>

app/views/partials/_image.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Upload Photo', upload_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<section>
  <div class="container">
    <!-- Alerts & Messages -->
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

  </div><!-- /.container -->
</section>

app/views/partials/_login_modal.html.erb
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>

<h2>Modal Login Form</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">

  <form class="modal-content animate" action="/action_page.php">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="img_avatar2.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <button type="submit">Login</button>
      <input type="checkbox" checked="checked"> Remember me
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

app/views/partials/_post_comments.html.erb
<!-- Comments -->
<div class="comments">

</div>

app/views/partials/_search.html.erb
<% if params[:controller] == 'posts' %>
  <%= form_tag(posts_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts",  class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% elsif params[:controller] == 'categories' %>
  <%= form_tag(categories_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Categories",  class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% elsif params[:controller] == 'photos' %>
  <%= form_tag(photos_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Photos",  class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% else %>
  <%= form_tag(root_path, :method => "get", id: "search-form", class:"search-form pull-right") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search",  class:'form-control' %>
    </div>
    <%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'posts' %>
	<div class="list-group">
		<% @categories.each do |category| %>
			<%= link_to category.name, category_path(category.id), class:'list-group-item' %>
		<% end %>
	</div>
<% end %>

app/views/partials/_signup_login.html.erb
<%# <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"  rel="stylesheet">

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
      <div class="col-md-4">
    
      <h4>Click "Create new account?"</h4>

      <div class="flip">
        <div class="card"> 

          <div class="face front">   
            <div class="panel panel-default">
              <form class="form-horizontal">
                <br>
                <h1 class="text-center">LOGO</h1>
                <br>
                <input class="form-control" placeholder="Username"/>
                <input class="form-control" placeholder="Password"/>
                <p class="text-right"><a href="">Forgot Password</a></p>
                <button class="btn btn-primary btn-block">LOG IN</button>
                <hr>
                <p class="blue">Sign in with</p>
                <p><i class="fa fa-facebook-f fa-lg"></i><i class="fa fa-twitter fa-lg"></i></p>
                <hr>
                <p class="text-center">
                  <a href="#" class="fliper-btn">Create new account?</a>
                </p>
              </form>
            </div>
          </div> 

          <div class="face back"> 
            <div class="panel panel-default">
              <form class="form-horizontal">
                <br>
                <h1 class="text-center">LOGO</h1>
                <br>
                <label>Basic Information</label>
                <input class="form-control" placeholder="Fullname"/>
                <input class="form-control" placeholder="Email"/>
                <label>Private Information</label>
                <input class="form-control" placeholder="Password"/>
                <input class="form-control" placeholder="Mobile Number"/>
                <button class="btn btn-primary btn-block">SIGN UP</button>
                <p class="text-center">
                  <a href="#" class="fliper-btn">Already have an account?</a>
                </p> 
              </form>
            </div>
          </div>

        </div>   
      </div>

      </div>
    <div class="col-md-4"></div>
  </div>
</div><!-- /.container --> %>



<!-- Large modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Login modal</button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    ×</button>
                <h4 class="modal-title" id="myModalLabel">
                    Login/Registration - <a href="http://www.jquery2dotnet.com">jquery2dotnet.com</a></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8" style="border-right: 1px dotted #C2C2C2;padding-right: 30px;">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#Login" data-toggle="tab">Login</a></li>
                            <li><a href="#Registration" data-toggle="tab">Registration</a></li>
                        </ul>
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div class="tab-pane active" id="Login">
                                <form role="form" class="form-horizontal">
                                <div class="form-group">
                                    <label for="email" class="col-sm-2 control-label">
                                        Email</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="email1" placeholder="Email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1" class="col-sm-2 control-label">
                                        Password</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="exampleInputPassword1" placeholder="Email" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-2">
                                    </div>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary btn-sm">
                                            Submit</button>
                                        <a href="javascript:;">Forgot your password?</a>
                                    </div>
                                </div>
                                </form>
                            </div>
                            <div class="tab-pane" id="Registration">
                                <form role="form" class="form-horizontal">
                                <div class="form-group">
                                    <label for="email" class="col-sm-2 control-label">
                                        Name</label>
                                    <div class="col-sm-10">
                                        <div class="row">
                                            <div class="col-md-3">
                                                <select class="form-control">
                                                    <option>Mr.</option>
                                                    <option>Ms.</option>
                                                    <option>Mrs.</option>
                                                </select>
                                            </div>
                                            <div class="col-md-9">
                                                <input type="text" class="form-control" placeholder="Name" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email" class="col-sm-2 control-label">
                                        Email</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="email" placeholder="Email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="mobile" class="col-sm-2 control-label">
                                        Mobile</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="mobile" placeholder="Mobile" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-sm-2 control-label">
                                        Password</label>
                                    <div class="col-sm-10">
                                        <input type="password" class="form-control" id="password" placeholder="Password" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-2">
                                    </div>
                                    <div class="col-sm-10">
                                        <button type="button" class="btn btn-primary btn-sm">
                                            Save & Continue</button>
                                        <button type="button" class="btn btn-default btn-sm">
                                            Cancel</button>
                                    </div>
                                </div>
                                </form>
                            </div>
                        </div>
                        <div id="OR" class="hidden-xs">
                            OR</div>
                    </div>
                    <div class="col-md-4">
                        <div class="row text-center sign-with">
                            <div class="col-md-12">
                                <h3>
                                    Sign in with</h3>
                            </div>
                            <div class="col-md-12">
                                <div class="btn-group btn-group-justified">
                                    <a href="#" class="btn btn-primary">Facebook</a> <a href="#" class="btn btn-danger">
                                        Google</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>