config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  get 'upload' => 'photos#new', :as => :upload
  # resources :categories
  resources :photo_comments, only: [:show, :create, :destroy]
  resources :photos, only: [:new, :create, :update]
  resources :post_comments, only: [:show, :create, :destroy]
  resources :posts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy, :edit]

  resources :posts do
    resources :post_comments
  end

  resources :photos do
    resources :photo_comments
  end

  namespace :admin do
    resources :categories
    resources :photo_comments
    resources :photos
    resources :post_comments
    resources :posts
    resources :sessions, except: [:index, :edit]
    resources :users
  end

  namespace :admin do
    get 'sessions/create'
    get "login" => "sessions#new", :as => "login"
    get "logout" => "sessions#destroy", :as => "logout"
  end

  # namespace :admin do
  #   get "login" => "sessions#new", :as => "login"
  # end

  # namespace :admin do
  #   get 'sessions/create'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#page'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :photos
  # validates :image_title, presence: true

  has_many :posts
  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :verify_is_admin

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('name ASC').paginate(:per_page => 10, :page => params[:page])
    else
      @categories = Category.all.order('name ASC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @photos = @category.photos
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else    
      render 'new'
    end
  end


  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @photoss = @category.photos
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else    
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "#{@category.name} Category Removed"
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
# class CategoriesController < ApplicationController
#   def new
#     @category = Category.new
#   end

#   def create
#     @category = Category.new(category_params)
#     if @category.save
#       flash[:notice] = "Category Created"
#       # redirect_to root_path
#     else
#       render 'new'
#     end
#   end

#   def edit
#     @category = Category.find(params[:id])
#     @categories = Category.all
#     @category_posts = @category.category_posts
#     @photos = @category.category_photos
#   end

#   def update
#     @category = Category.find(params[:id])
#     if @category.update(category_params)
#       flash[:notice] = "Category Updated"
#       redirect_to category_path(params[:id])
#     else
#       render 'edit'
#     end
#   end

#   def show
#     @category = Category.find(params[:id])
#     @categories = Category.all
#     @category_posts = @category.posts
#     # @photos = @category.category_photos
#   end

#   private
#   def category_params
#     params.require(:category).permit(:name)
#   end
# end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>Edit Category</h2>

<div class='photo-upload-form'>
  <%= form_for [:admin, @category] do |f| %>
  <!-- Check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%=link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
  <% end %>
</div>

app/views/admin/categories/index.html.erb
<div id="user_nav" class="pull-right"> 
  <% if current_user %>
    <h5>Logged In as <%= current_user.username.capitalize %></h5>
    <%= link_to 'Log Out', admin_logout_path, class:'btn btn-cancel pull-right' %>
    <% else %>
    <%= link_to 'Log In', admin_login_path, class:'btn btn-info' %>
  <% end %>
</div>

<h2 class="page-header">Manage Categories</h2>
<% if @categories.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Category Title</th>
      <th>Create Date</th>
      <th><%= link_to "Add Category", new_admin_category_path, class:'btn btn-addnew' %></th>
    </tr>
  
    <% @categories.each do |category|%>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= link_to "Edit", edit_admin_category_path(category), class:'btn  btn-primary' %> <%= link_to "Delete", admin_category_path(category),   class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'}   %></td>
    </tr>
    <% end %>
  </table>
  <%= will_paginate @categories %>
<% else %>
  <p>Sorry, No Category Was Found.</p>
<% end %>

app/views/admin/categories/new.html.erb
<h2>Add New Category</h2>

<div class='photo-upload-form'>
  <%= form_for [:admin, @category] do |f| %>
  <!-- Check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%=link_to "Cancel", admin_categories_path, class:'btn btn-default' %>
  <% end %>
</div>