config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  get 'upload' => 'photos#new', :as => :upload
  # resources :categories
  resources :photo_comments, only: [:show, :create, :destroy]
  resources :photos, only: [:new, :create, :update]
  resources :post_comments, only: [:show, :create, :destroy]
  resources :posts, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:destroy, :edit]

  resources :posts do
    resources :post_comments
  end

  resources :photos do
    resources :photo_comments
  end

  namespace :admin do
    resources :categories
    resources :photo_comments
    resources :photos
    resources :post_comments
    resources :posts
    resources :sessions, except: [:index, :edit]
    resources :users
  end

  namespace :admin do
    get 'sessions/create'
    get "login" => "sessions#new", :as => "login"
    get "logout" => "sessions#destroy", :as => "logout"
  end

  # namespace :admin do
  #   get "login" => "sessions#new", :as => "login"
  # end

  # namespace :admin do
  #   get 'sessions/create'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#page'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  username      :string
#  email         :string
#  password_hash :string
#  password_salt :string
#  is_admin      :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts
  has_many :post_comments
  has_many :photos
  has_many :photo_comments

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.search(query)
    where("username like ? OR email like ?", "%#{query}%", "%#{query}%")
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :verify_is_admin
  
  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('username ASC').paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.order('username ASC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else    
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else    
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "#{@user.username} User Removed"
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Oh heyy #{@user.username}! You may now Log In"
      redirect_to new_session_path
      # redirect_to photos_path
    else    
      flash.now.alert = 'Invalid or Imcomplete Entry'
      # redirect_to root_path
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div id="user_nav" class="pull-right"> 
  <% if current_user %>
    Logged In as <%= current_user.username %>
    <%= link_to 'Log Out', root_path, class:'btn btn-info' %>
    <% else %>
    <%= link_to 'Log In', admin_login_path %>
  <% end %>
</div>

<h2>Edit User</h2>

<div class='photo-upload-form'>
  <%= form_for [:admin, @user] do |f| %>
  <!-- Check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :new_password %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>
  <br>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%=link_to "Cancel", admin_users_path, class:'btn btn-default' %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div id="user_nav" class="pull-right"> 
  <% if current_user %>
    <h5>Logged In as <%= current_user.username.capitalize %></h5>
    <%= link_to 'Log Out', admin_logout_path, class:'btn btn-cancel pull-right' %>
    <% else %>
    <%= link_to 'Log In', admin_login_path, class:'btn btn-info' %>
  <% end %>
</div>

<h2 class="page-header">Manage Users</h2>
<% if @users.exists? %>
  <table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Date Created</th>
    <th><%= link_to "Add New User", new_admin_user_path, class:'btn btn-addnew' %></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= link_to"Edit", edit_admin_user_path(user), class:'btn btn-primary' %> <%= link_to"Delete", admin_user_path(user), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </table>
  <%= will_paginate @users %>
<% else %>
  <p>Sorry, No User Was Found.</p>
<% end %>

app/views/admin/users/new.html.erb
<h2>Welcome To CheekChubby</h2>

<div class='photo-upload-form'>
  <%= form_for [:admin, @user] do |f| %>
  <!-- Check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>
  <br>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%=link_to "Cancel", admin_users_path, class:'btn btn-default' %>
  <% end %>
</div>